CREATE TABLE salfordMOVE.dbo.RH_RESPONSE(
	rhResponseGUID UNIQUEIDENTIFIER NOT NULL,
	sensorID UNIQUEIDENTIFIER NOT NULL,
	responsePeriodGUID UNIQUEIDENTIFIER NOT NULL,
	readingID UNIQUEIDENTIFIER NOT NULL,
	zoneGUID UNIQUEIDENTIFIER NOT NULL,
	adjustedDate DATETIME NOT NULL,
	rhResponse FLOAT NOT NULL,
	CONSTRAINT PK_RH_RESPONSE PRIMARY KEY (rhResponseGUID),
	CONSTRAINT FK
)

CREATE TABLE salfordMove.dbo.RESPONSE_PERIODS(
	responsePeriodGUID UNIQUEIDENTIFIER NOT NULL,
	responsePeriodName
)

CREATE TABLE salfordMove.sbo.MATERIAL_TYPES(

)

CREATE TABLE salfordMove.dbo.ZONES(

)